### ISSUE TITLE
dumpvuser error on U7

### ISSUE THREAD

**Issue by ttosch** [Manko10/vmailmgr-chpw-cgi#1]
Hi Janek,
I tried to run this on a U7 and it fails with the error message "User not found or wrong password entered." even though the data is correct. After a bit of debugging, I found out that the call to dumpvuser failed with the error "Can't change to home directory". Any ideas what might be going on here? Thanks! T.

**Comment by phoerious** [comment]
U7 has SELinux rules that prevent you from accessing the home directory. You need to set the proper labels on the full file path to allow access.

**Comment by ttosch** [comment]
This explains it, thanks a lot! I just tried to figure out which labels I need, but I have never really played around with SELinux before and I'm a bit lost. Have you done this before, so that you could tell me which labels I need to set?

**Comment by phoerious** [comment]
```
chcon -t httpd_sys_content_t /home/xyz/...
```

Should do it. You've got to apply that to the whole path down to the user database files, though.

**Comment by ttosch** [comment]
Awesome, thanks! How about adding a hint in README to help other future U7 users?
This one worked for me:
`chcon -t httpd_sys_content_t /home/<space>`
`chcon -t httpd_sys_content_t /home/<space>/passwd.cdb`
